public class UmarRahim {
    public static void main(String[] args) {
        System.out.println("Personal Profile of UmarRahim");
        System.out.println("I am born in India, but I am currently living in Malaysia.");
        System.out.println("I chose Bachelor of Science in hopes of pursuing a career in medicine, but i am taking this course sincy technology is my hobby");
        System.out.println("In my free time, i either play games or binge watch anime");
        System.out.println("I also like to swim, gym, and draw when i am feeling inspired.");
        System.out.println("These are my initials:");
        System.out.println(" ██╗░░░██╗██████╗░ ");
        System.out.println(" ██║░░░██║██╔══██╗ ");
        System.out.println(" ██║░░░██║██████╔╝ ");
        System.out.println(" ██║░░░██║██╔══██╗ ");
        System.out.println(" ╚██████╔╝██║░░██║ ");
        System.out.println(" ░╚═════╝░╚═╝░░╚═╝ ");
        System.out.println(" ");
    }
}
